### ISSUE TITLE
你好，不知道是否有兴趣写一个教程

### ISSUE THREAD

**Issue by spoonysonny** [namco1992/voicetools#5]
图文教程结合来说明这个项目的使用方法，我很期待能将它在树莓派实验室博客 shumeipai.nxez.com 上分享给大家。

一时找不到联系方式， 不好意思以Issues方式沟通，希望没惊扰到你。

**Comment by namco1992** [comment]
你好，可以通过 namco1992@gmail.com 联系。还有些问题想请教，所以我们通过邮件沟通吧，谢谢。
